### ISSUE TITLE
Memory problem (how to fix it ?)

### ISSUE THREAD

**Issue by DreamDrum** [nousr/koi#16]
Hello, i have some problem in the final step, when i click on "dream" that don't work at all, that say :

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 7.33 GiB already allocated; 0 bytes free; 7.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
127.0.0.1 - - [02/Sep/2022 18:02:39] "POST /api/img2img HTTP/1.1" 500 -

Do you know how to fix it ? I don't understand Python very well or Pytorch, i really need help for this

**Comment by jpic** [comment]
Same, I'm currently attending a friend having this issue, tb:

```
Traceback (most recent call last):
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\[http://app.py](https://t.co/kZMjEtDEBQ)", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\[http://app.py](https://t.co/kZMjEtDEBQ)", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\[http://app.py](https://t.co/kZMjEtDEBQ)", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\[http://app.py](https://t.co/kZMjEtDEBQ)", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\DREAM\[http://server.py](https://t.co/7wgBPKYH6e)", line 48, in img2img
    return_image = pipe(
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\DREAM\diffusers\src\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_img2img.py", line 146, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings)["sample"]
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\[http://module.py](https://t.co/4PEdcfcnrX)", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DREAM\diffusers\src\diffusers\models\unet_2d_condition.py", line 150, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\[http://module.py](https://t.co/4PEdcfcnrX)", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DREAM\diffusers\src\diffusers\models\unet_blocks.py", line 505, in forward
    hidden_states = attn(hidden_states, context=encoder_hidden_states)
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\[http://module.py](https://t.co/4PEdcfcnrX)", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DREAM\diffusers\src\diffusers\models\[http://attention.py](https://t.co/vRpwfhnEmj)", line 118, in forward
    x = block(x, context=context)
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\[http://module.py](https://t.co/4PEdcfcnrX)", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DREAM\diffusers\src\diffusers\models\[http://attention.py](https://t.co/vRpwfhnEmj)", line 140, in forward
    x = self.attn1(self.norm1(x)) + x
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\[http://module.py](https://t.co/4PEdcfcnrX)", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DREAM\diffusers\src\diffusers\models\[http://attention.py](https://t.co/vRpwfhnEmj)", line 200, in forward
    out = torch.einsum("b i j, b j d -> b i d", attn, v)
  File "C:\Users\DREAM\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\[http://functional.py](https://t.co/Bmv4Ac5t4F)", line 330, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 8.00 GiB total capacity; 6.92 GiB already allocated; 0 bytes free; 7.33 GiB ved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memanagement and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by nousr** [comment]
e5531bb55f51bdf6097768391596c7d1c7286960 should be fixed! can you give it a shot now?
