### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by Porkechebure** [nousr/koi#30]
This happens after following every instruction and trying to draw

Followed all what it's written in readme.md

Full lot:
`[2022-09-06 03:37:08,913] ERROR in app: Exception on /api/img2img [POST]
Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Shadow\Downloads\koi-main\koi-main\server.py", line 51, in img2img
    return_image = pipe(
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Shadow\Downloads\dif\diffusers\src\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_img2img.py", line 108, in __call__
    init_latents = self.scheduler.add_noise(init_latents, noise, timesteps).to(self.device)
  File "C:\Users\Shadow\Downloads\dif\diffusers\src\diffusers\schedulers\scheduling_pndm.py", line 284, in add_noise
    sqrt_alpha_prod = self.alphas_cumprod[timesteps] ** 0.5
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`

**Comment by nousr** [comment]
am i understanding correctly that you are trying to run inference on your CPU?

I would not recommend this as it will take an extremely long time to render results. I recommend using google colab as an alternative

**Comment by Porkechebure** [comment]
> am i understanding correctly that you are trying to run inference on your CPU?
> 
> I would not recommend this as it will take an extremely long time to render results. I recommend using google colab as an alternative

No, I have a powerful gpu and I didn't set anything to run it on CPU.
What is wrong  with my config?

**Comment by nousr** [comment]
> No, I have a powerful gpu and I didn't set anything to run it on CPU.


hmmm, do you have a AMD gpu by chance?

**Comment by Porkechebure** [comment]
> > No, I have a powerful gpu and I didn't set anything to run it on CPU.
> 
> hmmm, do you have a AMD gpu by chance?

Nope:
![image](https://user-images.githubusercontent.com/3466040/188529446-0a67d8d6-da08-425d-973a-236211127c84.png)

**Comment by nousr** [comment]
you sent a screenshot of your CPU processor -- could you send a screenshot of your GPU, please?

**Comment by Porkechebure** [comment]
> you sent a screenshot of your CPU processor -- could you send a screenshot of your GPU, please?

![image](https://user-images.githubusercontent.com/3466040/188529891-ceb5af6b-c2d0-47b4-ad54-351545af2448.png)

As I said I've run successfully multiple versions of SD, this GPU is fine for SD

**Comment by Porkechebure** [comment]
> you sent a screenshot of your CPU processor -- could you send a screenshot of your GPU, please?

Any news?
What it could be?

**Comment by Porkechebure** [comment]
> you sent a screenshot of your CPU processor -- could you send a screenshot of your GPU, please?

So it happened that I had the nyghtly pytorch preview, and that was the issue. Had to reinstall the stable version with:
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

Now, the images produced are black

![image](https://user-images.githubusercontent.com/3466040/188599732-87e107f4-b268-44b8-a1a1-0d40b370d941.png)


What's the problem now?
