### ISSUE TITLE
Error getting image to krita after successful generation on collab

### ISSUE THREAD

**Issue by vo7na8** [nousr/koi#53]
after image generation on colab i get this piece of logs:
100%
19/19 [00:05<00:00, 3.70it/s]
ERROR:__main__:Exception on /api/img2img [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-3-35b40b736f48>", line 76, in img2img
    )["sample"][0]
  File "/usr/local/lib/python3.7/dist-packages/diffusers/utils/outputs.py", line 88, in __getitem__
    return inner_dict[k]
KeyError: 'sample'
INFO:werkzeug:127.0.0.1 - - [03/Nov/2022 14:42:37] "POST /api/img2img HTTP/1.1" 500 -

I think that image generated sucsessfully, but it somehow cannot be transferred to my pc. How can i fix this?

**Comment by brunolm** [comment]
Fix: https://github.com/nousr/koi/issues/51#issuecomment-1751548449
